### ISSUE TITLE
scapy and packets lost

### ISSUE THREAD

**Issue by llazzaro** [roobixx/harbinger#2]
Hi!

I have a similar project as harbinger, but right now is not public yet.
After several weeks of using scapy on my raspberrypis I found that scapy loses like 98% of the packets. I found a way to improve scapy using libpcap, but again I was losing 90% (check conf.use_pcap = True).
To avoid losing packets I recommend to use the aircrack suite. just save all the traffic, then you plug the raspberry and process the saved data with scapy, avoid doing it in realtime.

Hope it helps!

**Comment by roobixx** [comment]
There are reasons beyond the code here for having realtime processing, so your aircrack solution would not work in this particular case. In others, you are absolutely correct.
